In [0]:
from google.colab import files
import io


uploaded = files.upload()

Saving road.txt to road.txt


In [0]:
import pandas as pd
import numpy as np



In [0]:

environment = pd.read_csv("environment2.txt", sep="\t", header=None)
environment.columns = ["text"]
safety = pd.read_csv("co_make.txt", sep="\t", header=None)
safety.columns = ["text"]
community = pd.read_csv("community2.txt", sep="\t", header=None)
community.columns = ["text"]
roads = pd.read_csv("road.txt", sep="\t", header=None)
roads.columns = ["text"]

In [0]:
pd.set_option('display.max_colwidth', -1)


In [0]:
from bs4 import BeautifulSoup
environment['text'] = [BeautifulSoup(text).get_text() for text in environment['text'] ]
safety['text'] = [BeautifulSoup(text).get_text() for text in safety['text'] ]
community['text'] = [BeautifulSoup(text).get_text() for text in community['text'] ]
roads['text'] = [BeautifulSoup(text).get_text() for text in roads['text'].astype(str) ]

/usr/local/lib/python3.6/dist-packages/bs4/__init__.py:336: UserWarning: "http://www.green-innovations.asn.au/" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup
/usr/local/lib/python3.6/dist-packages/bs4/__init__.py:336: UserWarning: "http://www.princeton.edu/~browning/snow.html" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup
/usr/local/lib/python3.6/dist-packages/bs4/__init__.py:336: UserWarning: "http://www.deh.gov.au/esd/national/nsesd/index.html" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed tha

In [0]:
environment['label']='environment'
safety['label']='safety'
community['label']='community'
roads['label']='roads'


environment = environment.iloc[:700]
community = community.iloc[:700]
roads = roads.iloc[:700]

data = pd.concat([environment, safety, community, roads]) 


In [0]:
data

In [0]:
import pandas as pd
import numpy as np
from nltk.tokenize import word_tokenize
from nltk import pos_tag
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.preprocessing import LabelEncoder
from collections import defaultdict
from nltk.corpus import wordnet as wn
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import model_selection, naive_bayes, svm
from sklearn.metrics import accuracy_score

In [0]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(data['text'], data['label'],test_size=0.3)

In [0]:
Encoder = LabelEncoder()
y_train = Encoder.fit_transform(y_train)
y_test = Encoder.fit_transform(y_test)

In [0]:
Tfidf_vect = TfidfVectorizer(max_features=5000)
Tfidf_vect.fit(data['text'])
Train_X_Tfidf = Tfidf_vect.transform(x_train)
Test_X_Tfidf = Tfidf_vect.transform(x_test)

In [0]:
# fit the training dataset on the NB classifier
Naive = naive_bayes.MultinomialNB()
Naive.fit(Train_X_Tfidf,y_train)
# predict the labels on validation dataset
predictions_NB = Naive.predict(Test_X_Tfidf)
# Use accuracy_score function to get the accuracy
print("Naive Bayes Accuracy Score -> ",accuracy_score(predictions_NB, y_test)*100)

Naive Bayes Accuracy Score ->  87.0083432657926


In [0]:
text=["this playground is dangerous. someone could break an arm on the jungle gym"]
testing = Tfidf_vect.transform(text)
Naive.predict(testing)

array([0])

In [0]:
text2=["we should switch to green energy and use solar panels to keep the planet safe"]
testing2 = Tfidf_vect.transform(text2)
Naive.predict(testing2)

array([1])

In [0]:
text2=["the homeowners association is very unresponsive. they don't return my calls"]
testing2 = Tfidf_vect.transform(text2)
Naive.predict(testing2)

array([0])

In [0]:
text2=["the building next door is not up to code"]
testing2 = Tfidf_vect.transform(text2)
Naive.predict(testing2)

array([0])

In [0]:
text2=["roads"]
testing2 = Tfidf_vect.transform(text2)
Naive.predict(testing2)

array([2])

In [0]:
import pickle
# save the model to disk
filename = 'finalized_model.sav'


In [0]:
pickled = pickle.dump(Naive, open(filename, 'wb'))

In [0]:
files.download(filename)

In [0]:
pkl_filename = "pickle_model.pkl"
with open(pkl_filename, 'wb') as file:
    pickle.dump(Naive, file)

In [0]:
files.download(pkl_filename)

In [0]:
data.to_csv('train_test.csv')
files.download('train_test.csv')

In [0]:
pkl_filename = "Tfidf_vect.pkl"
with open(pkl_filename, 'wb') as file:
    pickle.dump(Tfidf_vect, file)

In [0]:
files.download(pkl_filename)

In [0]:
#pickle.dump(Tfidf_vect, open("tfidf1.pkl", "wb"))


In [0]:
pkl_filename2 = "vocabulary.pkl"
with open(pkl_filename2, 'wb') as file:
    pickle.dump(Tfidf_vect.vocabulary_, file)

In [0]:
files.download(pkl_filename2)